// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmVszzsmym0u4ujrwU4eL0s2ZIkqNcoeQ',
    appId: '1:643270209299:web:your_web_app_id_here',
    messagingSenderId: '643270209299',
    projectId: 'faculty-lms',
    authDomain: 'faculty-lms.firebaseapp.com',
    storageBucket: 'faculty-lms.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMtqPaOMoRBjquEITk7ASDydsCBNOdNSM',
    appId: '1:400787893773:android:dff5ad2c531b627e3def44',
    messagingSenderId: '400787893773',
    projectId: 'ilmvista-instructor',
    storageBucket: 'ilmvista-instructor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqkj97TdOyXeM_0Q5kfw5Lk_Rnjn3h9t4',
    appId: '1:400787893773:ios:971cfb20dcb3a3893def44',
    messagingSenderId: '400787893773',
    projectId: 'ilmvista-instructor',
    storageBucket: 'ilmvista-instructor.firebasestorage.app',
    iosBundleId: 'com.spagreen.faculty.instructor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQjPa5dlGpt6EFgeuOgRzaBSelkdEft4c',
    appId: '1:643270209299:macos:your_macos_app_id_here',
    messagingSenderId: '643270209299',
    projectId: 'faculty-lms',
    storageBucket: 'faculty-lms.appspot.com',
    iosBundleId: 'com.spagreen.lms.user.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmVszzsmym0u4ujrwU4eL0s2ZIkqNcoeQ',
    appId: '1:643270209299:windows:your_windows_app_id_here',
    messagingSenderId: '643270209299',
    projectId: 'faculty-lms',
    authDomain: 'faculty-lms.firebaseapp.com',
    storageBucket: 'faculty-lms.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDmVszzsmym0u4ujrwU4eL0s2ZIkqNcoeQ',
    appId: '1:643270209299:linux:your_linux_app_id_here',
    messagingSenderId: '643270209299',
    projectId: 'faculty-lms',
    authDomain: 'faculty-lms.firebaseapp.com',
    storageBucket: 'faculty-lms.appspot.com',
  );
}